# [START cloudbuild_steps]
steps:

  # [START cloudbuild_lb4_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'build', '-t', 'gcr.io/co-corptalentum-gcp/lb4_example:${TAG_NAME}', '.' ]
    entrypoint: 'bash'
    args: ['-c',
      'version=$TAG_NAME && docker build -t gcr.io/co-corptalentum-gcp/lb4_example:${version//./-} .']
  # [END cloudbuild_lb4_image_yaml]

substitutions:
    _SUB_VALUE: ${TAG_NAME}

  # [START cloudbuild_lb4_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',  'gcr.io/co-corptalentum-gcp/lb4_example:${TAG_NAME}' ]
  # [END cloudbuild_lb4_push_yaml]
