# [START cloudbuild_steps]
steps:

  # [START cloudbuild_lb4_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:${_MY_TAG}', '.' ]
  # [END cloudbuild_lb4_image_yaml]

  # [START cloudbuild_lb4_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',  'gcr.io/$PROJECT_ID/$REPO_NAME:${_MY_TAG}' ]
  # [END cloudbuild_lb4_push_yaml]

  # [START cloudbuild_lb4_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '.' ]
  # [END cloudbuild_lb4_image_yaml]

  # [START cloudbuild_lb4_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',  'gcr.io/$PROJECT_ID/$REPO_NAME:latest' ]
  # [END cloudbuild_lb4_push_yaml]

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', 'lb4exampleback', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:${_MY_TAG}', '--cluster', 'cluster-prod', '--cluster-location', 'us-east1-d', '--namespace', 'example', '--platform', 'gke']

#https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run?hl=es-419#cloud-run-for-anthos_1
#https://stackoverflow.com/questions/61944660/env-step-parameter-in-cloudbuild-yaml-file-not-settings-environment-variable

# Deploy container image to Cloud Run for Anthos
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args: ['run', 'deploy', 'lb4exampleback', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '--cluster', 'cluster-prod', '--cluster-location', 'us-east1-d', '--platform', 'gke', '--namespace', 'example']

# Deploy container image to Cloud Run for Anthos
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'lb4-example'
    - '--namespace'
    - 'example'
    - '--max-instances'
    - '1'
    - '--update-config-maps'
    - 'hola=temporal'
    - '--image'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    - '--cluster'
    - 'cluster-prod'
    - '--cluster-location'
    - 'us-east1-d'
    - '--platform'
    - 'gke'
    - '--revision-suffix'
    - '""'

images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:latest

substitutions:
  _MY_TAG: ${TAG_NAME:1}
options:
  dynamic_substitutions: true
